### ISSUE TITLE
Vue component not showing up on the page.

### ISSUE THREAD

**Issue by jamgar** [jamgar/test-inertia#1]
--In the console I can see the data-page values being returned from the controller.
<img width="709" alt="Screen Shot 2020-08-21 at 7 21 53 AM" src="https://user-images.githubusercontent.com/14931684/90890213-2a678300-e37f-11ea-91f0-78ec5aea1488.png">

--The Pages seem to be compiled by webpack
<img width="221" alt="Screen Shot 2020-08-21 at 7 24 49 AM" src="https://user-images.githubusercontent.com/14931684/90890390-7f0afe00-e37f-11ea-9903-13142862d41b.png">

--No component displaying
<img width="692" alt="Screen Shot 2020-08-21 at 7 26 22 AM" src="https://user-images.githubusercontent.com/14931684/90890474-b1b4f680-e37f-11ea-993b-3d7905b64b0a.png">

**Comment by ledermann** [comment]
The console tab shows exactly what's going wrong:

```javascript
TypeError: Cannot read property 'dataset' of null
    at Proxy.render (application.js:29)
    at Vue._render (vue.runtime.esm.js:3528)
    at Vue.updateComponent (vue.runtime.esm.js:4056)
    at Watcher.get (vue.runtime.esm.js:4470)
    at new Watcher (vue.runtime.esm.js:4457)
    at mountComponent (vue.runtime.esm.js:4063)
    at Vue../node_modules/vue/dist/vue.runtime.esm.js.Vue.$mount (vue.runtime.esm.js:8402)
    at Module../app/javascript/packs/application.js (application.js:26)
    at __webpack_require__ (bootstrap:19)
    at bootstrap:83
```

The const `app` is null, because the code in `application.js` runs before the DOM is ready, so `#app` cannot be found. Fixing this is simple by changing `application.html`:

```diff
-   <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
+   <%= javascript_pack_tag 'application', defer: true %>
```

The `defer` tells the browser to render the DOM first, and load the script in background. The JS is executed after the DOM is ready: https://javascript.info/script-async-defer#defer

BTW: The Turbolinks stuff can be removed, because it's not needed with Inertia.js

After this change the Vue component is rendered as expected.
